repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
  - repo: https://github.com/quantco/pre-commit-mirrors-ruff
    rev: 0.0.291
    hooks:
      - id: ruff-conda
  - repo: https://github.com/quantco/pre-commit-mirrors-black
    rev: 23.9.1
    hooks:
      - id: black-conda
        args:
          - --safe
          - --target-version=py39
  - repo: https://github.com/quantco/pre-commit-mirrors-mypy
    rev: 1.5.1
    hooks:
      - id: mypy-conda
