name: Build
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version-changed: ${{ steps.version-metadata.outputs.changed }}
      new-version: ${{ steps.version-metadata.outputs.newVersion }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.9'
      - name: Install Python build
        run: pip install build
      - name: Build project
        run: python -m build
      - name: Upload package
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: artifact
          path: dist/*
      - uses: Quantco/ui-actions/version-metadata@adeb1cf49655487534b4ddaab09c3b7bdfd1d628 # v1.0.19
        id: version-metadata
        with:
          file: ./pyproject.toml
          token: ${{ secrets.GITHUB_TOKEN }}
          version-extraction-override: 'regex:version = "(.*)"'

  release:
    name: Publish package
    if: github.event_name == 'push' && github.repository == 'Quantco/polarify' && github.ref_name == 'main' && needs.build.outputs.version-changed == 'true'
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment: pypi
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: artifact
          path: dist
      - name: Publish package on PyPi
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Push v${{ needs.build.outputs.new-version }} tag
        run: |
          git tag v${{ needs.build.outputs.new-version }}
          git push origin v${{ needs.build.outputs.new-version }}
      - name: Create release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe
        with:
          generate_release_notes: true
          tag_name: v${{ needs.build.outputs.new-version }}
          draft: true
