name: Build
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version-changed: ${{ steps.version-metadata.outputs.changed }}
      new-version: ${{ steps.version-metadata.outputs.newVersion }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.9'
      - name: Install Python build
        run: pip install build
      - name: Build project
        run: python -m build
      - name: Upload package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: artifact
          path: dist/*
      - uses: Quantco/ui-actions/version-metadata@adeb1cf49655487534b4ddaab09c3b7bdfd1d628 # v1.0.19
        id: version-metadata
        with:
          file: ./pyproject.toml
          token: ${{ secrets.GITHUB_TOKEN }}
          version-extraction-override: 'regex:version = "(.*)"'

  release:
    name: Publish package
    if: github.event_name == 'push' && github.repository == 'Quantco/polarify' && github.ref_name == 'main' && needs.build.outputs.version-changed == 'true'
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    environment: pypi
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: artifact
          path: dist
      - name: Publish package on PyPi
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Push v${{ needs.build.outputs.new-version }} tag
        run: |
          git tag v${{ needs.build.outputs.new-version }}
          git push origin v${{ needs.build.outputs.new-version }}
      - name: Create release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          generate_release_notes: true
          tag_name: v${{ needs.build.outputs.new-version }}
          draft: true
