name: CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Unit tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - pl017
          - pl018
          - pl019
          - pl020
          - py39
          - py310
          - py311
          - py312
        # include:
        #   - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.14.28' }
        #   - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.15' }
        #   - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.16' }
        #   - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.17' }
        #   - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.18' }
        #   - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.19' }
        #   - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.20' }
        #   - { PYTHON_VERSION: 'python=3.10', POLARS_VERSION: '' }
        #   - { PYTHON_VERSION: 'python=3.11', POLARS_VERSION: '' }
        #   - { PYTHON_VERSION: 'python=3.12', POLARS_VERSION: '' }
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.4.3
        with:
          run-install: false
          pixi-url: https://transfer.sh/ukAUhXFepC/pixi-aarch64-apple-darwin
      - if: always()
        run: |
          set +e
          set -x
          which pixi
          cat `which pixi`
      - name: Install dependencies
        run: |
          pixi run --env ${{ matrix.env }} postinstall
          pixi run --env ${{ matrix.env }} pytest
      # - name: Run unittests
      #   uses: pavelzw/pytest-action@510c5e90c360a185039bea56ce8b3e7e51a16507
      #   with:
      #     custom-pytest: pixi run pytest
      #     report-title: ${{ matrix.PYTHON_VERSION }} ${{ matrix.POLARS_VERSION }}

  pre-commit-checks:
    # TODO: switch to pixi once there is a good way
    name: pre-commit
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Run pre-commit
        uses: quantco/pre-commit-conda@v1

  lint-workflow-files:
    name: Lint workflow files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      # https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
