name: CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -el {0}

jobs:
  linux-unittests:
    name: Unit tests Linux - ${{ matrix.PYTHON_VERSION }} ${{ matrix.POLARS_VERSION }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.14.28' }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.15' }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.16' }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.17' }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.18' }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.19' }
          - { PYTHON_VERSION: 'python=3.10', POLARS_VERSION: '' }
          - { PYTHON_VERSION: 'python=3.11', POLARS_VERSION: '' }
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.3.0
        with:
          run-install: false
      - name: Install dependencies
        # TODO: make prettier once there are feature flags
        # https://github.com/prefix-dev/pixi/issues/239
        run: |
          pixi add ${{ matrix.PYTHON_VERSION }} ${{ matrix.POLARS_VERSION }}
          pixi install
          pixi run postinstall
      - name: Run unittests
        uses: pavelzw/pytest-action@v2
        with:
          custom-pytest: pixi run pytest
          report-title: Unit tests Linux - ${{ matrix.PYTHON_VERSION }} ${{ matrix.POLARS_VERSION }}

  pre-commit-checks:
    # TODO: switch to pixi once there is a good way
    name: pre-commit
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      PRE_COMMIT_USE_MICROMAMBA: 1
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@db1df3ba9e07ea86f759e98b575c002747e9e757
      - name: Add micromamba to GITHUB_PATH
        run: echo "${HOME}/micromamba-bin" >> "$GITHUB_PATH"
      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0

  lint-workflow-files:
    name: Lint workflow files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      # https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
