name: CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -el {0}

jobs:
  linux-unittests:
    name: Unit tests Linux - Python ${{ matrix.PYTHON_VERSION }}
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      # TODO: move to action once it is available
      - name: Set up pixi
        run: |
          curl -fsSL https://raw.githubusercontent.com/prefix-dev/pixi/main/install/install.sh | bash
      - name: Install dependencies
        # TODO: make prettier once pixi supports it
        # https://github.com/prefix-dev/pixi/issues/239
        run: |
          pixi add python=${{ matrix.PYTHON_VERSION }}
          pixi install
          pixi run postinstall
      - name: Run unittests
        uses: pavelzw/pytest-action@v2
        with:
          custom-pytest: pixi run pytest
          report-title: Unit tests Linux - Python ${{ matrix.PYTHON_VERSION }}

  pre-commit-checks:
    # TODO: switch to pixi once there is a good way
    name: pre-commit
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      PRE_COMMIT_USE_MICROMAMBA: 1
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.5.2
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@875557da4ee020f18df03b8910a42203fbf02da1
      - name: Add micromamba to GITHUB_PATH
        run: echo "${HOME}/micromamba-bin" >> "$GITHUB_PATH"
      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0

  lint-workflow-files:
    name: Lint workflow files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      # https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
