name: CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Unit tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
          - pl014
          - pl015
          - pl016
          - pl017
          - pl018
          - pl019
          - pl020
          - py39
          - py310
          - py311
          - py312
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@632d17935141ec801697e2c359784b878adecbbe
        with:
          environments: ${{ matrix.env }}
          manifest-path: pyproject.toml
      - name: Run unittests
        uses: pavelzw/pytest-action@510c5e90c360a185039bea56ce8b3e7e51a16507
        with:
          custom-pytest: pixi run -e ${{ matrix.env }} coverage
          report-title: ${{ matrix.env }}
      - name: Upload coverage reports to Codecov
        if: matrix.env == 'py312'
        uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml

  pre-commit-checks:
    # TODO: switch to pixi once there is a good way
    name: pre-commit
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Run pre-commit
        uses: quantco/pre-commit-conda@v1

  lint-workflow-files:
    name: Lint workflow files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      # https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
