name: CI
on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.PYTHON_VERSION }} ${{ matrix.POLARS_VERSION }} ${{ matrix.os }}
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.14.28', os: ubuntu-latest }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.15', os: ubuntu-latest }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.16', os: ubuntu-latest }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.17', os: ubuntu-latest }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.18', os: ubuntu-latest }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: 'polars=0.19', os: ubuntu-latest }
          - { PYTHON_VERSION: 'python=3.10', POLARS_VERSION: '', os: ubuntu-latest }
          - { PYTHON_VERSION: 'python=3.11', POLARS_VERSION: '', os: ubuntu-latest }
          - { PYTHON_VERSION: 'python=3.12', POLARS_VERSION: '', os: ubuntu-latest }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: '', os: macos-latest }
          - { PYTHON_VERSION: 'python=3.9', POLARS_VERSION: '', os: windows-latest }
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.3.0
        with:
          run-install: false
      - name: Install dependencies
        # TODO: make prettier once there are feature flags
        # https://github.com/prefix-dev/pixi/issues/239
        run: |
          pixi add ${{ matrix.PYTHON_VERSION }} ${{ matrix.POLARS_VERSION }}
          pixi install
          pixi run postinstall
      - name: Run unittests
        uses: pavelzw/pytest-action@342008861c5f93d3689ebf656acb26170b3ff161
        with:
          custom-pytest: pixi run pytest
          report-title: ${{ matrix.PYTHON_VERSION }} ${{ matrix.POLARS_VERSION }} ${{ matrix.os }}

  pre-commit-checks:
    # TODO: switch to pixi once there is a good way
    name: pre-commit
    timeout-minutes: 30
    runs-on: ubuntu-latest
    env:
      PRE_COMMIT_USE_MICROMAMBA: 1
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@54d4d5980e1a4aa7cdc8b050cf2d19b7e262ce18
      - name: Add micromamba to GITHUB_PATH
        run: echo "${HOME}/micromamba-bin" >> "$GITHUB_PATH"
      - name: Install Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0

  lint-workflow-files:
    name: Lint workflow files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      # https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
